In [1]:
import numpy as np

In [3]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

v est un vecteur de dimension 1

In [4]:
type(v)

numpy.ndarray

In [10]:
tailles=[1.83, 1.85, 1.65, 1.90, 1.72, 1.89, 1.59, 1.68]
print(type(tailles))

poids= [69, 75, 79, 120, 55, 89, 66, 80]
print(type(poids))

<class 'list'>
<class 'list'>


Calculons l'IMC

In [13]:
tailles_array=np.array(tailles)

poids_array=np.array(poids)

print(type(tailles_array))
print(type(poids_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
imc = poids_array /tailles_array**2
imc

array([20.60378035, 21.9138057 , 29.0174472 , 33.24099723, 18.59113034,
       24.91531592, 26.10656224, 28.3446712 ])

In [16]:
imc>25

array([False, False,  True,  True, False, False,  True,  True])

In [17]:
imc[imc>25]

array([29.0174472 , 33.24099723, 26.10656224, 28.3446712 ])

matrice: est une liste emboitée ou ilbriquée i.e une liste dans une liste

In [18]:
M= np.array([ [1 ,3],[2,4] ])
M

array([[1, 3],
       [2, 4]])

In [19]:
type(M)

numpy.ndarray

creation tb numpy à partir d'une matrice

In [22]:
M = np.array([[1,3],[2,4]])
M

array([[1, 3],
       [2, 4]])

on parle de tableau numpy à 02 dimensions

In [23]:
M[0,0]

1

In [24]:
M[1,1]

4

In [25]:
M[:,1]

array([3, 4])

In [26]:
M[:,0]

array([1, 2])

In [27]:
M[0]

array([1, 3])

In [29]:
M[0:]

array([[1, 3],
       [2, 4]])

creation d'un tableau numpy à deux dimensions

In [30]:
family_data=np.array([tailles,poids])
family_data

array([[  1.83,   1.85,   1.65,   1.9 ,   1.72,   1.89,   1.59,   1.68],
       [ 69.  ,  75.  ,  79.  , 120.  ,  55.  ,  89.  ,  66.  ,  80.  ]])

In [31]:
family_data.shape

(2, 8)

In [33]:
family_data.ndim

2

In [35]:
M.ndim

2

In [36]:
M.shape

(2, 2)

In [41]:
print("deuxième membre:",family_data [:,1])

deuxième membre: [ 1.85 75.  ]


In [42]:
print("troisieme membre:", family_data [:,2])

troisieme membre: [ 1.65 79.  ]


In [43]:
tab_range= np.array(range(5))
tab_range

array([0, 1, 2, 3, 4])

In [44]:
np_arange= np.arange(5)
np_arange

array([0, 1, 2, 3, 4])

In [45]:
np_arange2= np.arange(1.0, 2.0, 0.1)
np_arange2

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [46]:
x= np.linspace(0., 10., 50)
x

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [47]:
len(x)

50